# Name - Subham Kedia
# UNI -  sk4355
# Research Assistant Task-2

In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sys

%matplotlib inline

In [2]:
state = pd.read_csv("bds_f_szst_release.csv") # reading the dataset 'firm size by state' and storing it in state

In [3]:
state['state'].unique()

array([ 1,  2,  4,  5,  6,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56])

#### Inter-state deregulation data taken from the link mentioned below. 
#### This gives us the respective years when inter-state deregulation was implemented for each state in the United States of America.

https://files.stlouisfed.org/files/htdocs/publications/review/03/07/Strahan.pdf



In [4]:
st_code = state['state'].unique() # storing the unique state codes which identifies each state from the 'state' column.
dict_year = {} # creating a dictionary which has years when inter-state deregulation was implemented for each state.
dict_year[1] = 1987
dict_year[2] = 1982
dict_year[4] = 1986
dict_year[5] = 1989
dict_year[6] = 1987
dict_year[8] = 1988
dict_year[9] = 1983
dict_year[10] = 1988
dict_year[11] = 1985
dict_year[12] = 1985
dict_year[13] = 1985
dict_year[15] = 1985
dict_year[16] = 1985
dict_year[17] = 1986
dict_year[18] = 1986
dict_year[19] = 1991
dict_year[20] = 1992
dict_year[21] = 1984
dict_year[22] = 1987
dict_year[23] = 1978
dict_year[24] = 1985
dict_year[25] = 1983
dict_year[26] = 1986
dict_year[27] = 1986
dict_year[28] = 1988
dict_year[29] = 1986
dict_year[30] = 1993
dict_year[31] = 1990
dict_year[32] = 1985
dict_year[33] = 1987
dict_year[34] = 1986
dict_year[35] = 1989
dict_year[36] = 1982
dict_year[37] = 1985
dict_year[38] = 1991
dict_year[39] = 1985
dict_year[40] = 1987
dict_year[41] = 1986
dict_year[42] = 1986
dict_year[44] = 1984
dict_year[45] = 1986
dict_year[46] = 1988
dict_year[47] = 1985
dict_year[48] = 1987
dict_year[49] = 1984
dict_year[50] = 1988
dict_year[51] = 1985
dict_year[53] = 1987
dict_year[54] = 1988
dict_year[55] = 1987
dict_year[56] = 1987
print(dict_year.keys()) # displaying the keys of the dictionary
print('---------------')
print(dict_year[1]) # gives us the year of implementation of inter-state deregulation for state '1' (ALABAMA).

dict_keys([1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56])
---------------
1987


In [5]:
# creating a dictionary which has the keys as year of implementation of inter-state deregulation.
# the value of the key gives us the number of states for which inter-state deregulation was implemented in that year.
count_dict = {}
for key in dict_year:
    if dict_year[key] not in count_dict:
        count_dict[dict_year[key]] = 1
    else:
        count_dict[dict_year[key]] = count_dict[dict_year[key]] + 1
print(count_dict.keys()) # displaying the keys of the dictionary.
print('----------------')
print(count_dict[1982]) # gives us the number of states which implemented inter-state deregulation in the year 1982.

dict_keys([1987, 1982, 1986, 1989, 1988, 1983, 1985, 1991, 1992, 1984, 1978, 1993, 1990])
----------------
2


In [6]:
count_dict

{1978: 1,
 1982: 2,
 1983: 2,
 1984: 3,
 1985: 11,
 1986: 10,
 1987: 9,
 1988: 6,
 1989: 2,
 1990: 1,
 1991: 2,
 1992: 1,
 1993: 1}

In [7]:
# adding a new column named 'deregulation' in the dataset for each state.
# all the entries of this column for a state is the implementation year of inter-state deregulation for that particular state.
for key in dict_year:
    state.loc[state['state']==key, 'deregulation'] = dict_year[key]
    
print(state[state['state'] == 1]['deregulation']) # gives us the 'deregulation' column for state-1 (ALABAMA).
# this is the implementation year of inter-state deregulation for state-1 (ALABAMA).
# all the entries of this particular column are the same.

0        1987.0
1        1987.0
2        1987.0
3        1987.0
4        1987.0
5        1987.0
6        1987.0
7        1987.0
8        1987.0
9        1987.0
10       1987.0
11       1987.0
612      1987.0
613      1987.0
614      1987.0
615      1987.0
616      1987.0
617      1987.0
618      1987.0
619      1987.0
620      1987.0
621      1987.0
622      1987.0
623      1987.0
1224     1987.0
1225     1987.0
1226     1987.0
1227     1987.0
1228     1987.0
1229     1987.0
          ...  
21426    1987.0
21427    1987.0
21428    1987.0
21429    1987.0
21430    1987.0
21431    1987.0
22032    1987.0
22033    1987.0
22034    1987.0
22035    1987.0
22036    1987.0
22037    1987.0
22038    1987.0
22039    1987.0
22040    1987.0
22041    1987.0
22042    1987.0
22043    1987.0
22644    1987.0
22645    1987.0
22646    1987.0
22647    1987.0
22648    1987.0
22649    1987.0
22650    1987.0
22651    1987.0
22652    1987.0
22653    1987.0
22654    1987.0
22655    1987.0
Name: deregulation, Leng

In [8]:
# creating an array which has all the unique firm sizes.
category = state['fsize'].unique()
print(category)

['a) 1 to 4' 'b) 5 to 9' 'c) 10 to 19' 'd) 20 to 49' 'e) 50 to 99'
 'f) 100 to 249' 'g) 250 to 499' 'h) 500 to 999' 'i) 1000 to 2499'
 'j) 2500 to 4999' 'k) 5000 to 9999' 'l) 10000+']


##### Difference in differences is a statistical technique used in econometrics and quantitative research in the social sciences that attempts to mimic an experimental research design using observational study data, by studying the differential effect of a treatment on a 'treatment group' versus a 'control group' in a natural experiment. It calculates the effect of a treatment (i.e., an explanatory variable or an independent variable) on an outcome (i.e., a response variable or dependent variable) by comparing the average change over time in the outcome variable for the treatment group, compared to the average change over time for the control group. 

#### Three different methods have been used in the analysis below to calculate the difference in difference value to study the effect of inter-state deregulation on firm size.

#### Method-1 = We consider the time period between 1985 to 1987 to calculate difference in difference. This time period is considered because highest number of states implemented inter-state deregulation in 1985, 1986 and 1987. We considered 1985 to 1987, making an assumption that atleast two years are required for any governmental change (new law) to show effect on the economy.

#### Method-2 = We consider the time period between 1985 to 1986 to calculate difference in difference. This time period is considered because highest number of states implemented inter-state deregulation in 1985, 1986 and 1987. We considered 1985 to 1986 to make sure there was an effect of implementation inter-state deregulation on the firm size.

#### Method-3 = We create a 3D matrix which compares the effect of inter-state deregulation between two states at a time for each firm size. This comparison is done between all the states. Now, there are 51 states in the dataset given. So, state-1 and state-2 are compared for all firm sizes, then state-1 and state-3 and then state-1 and state-4 and so on. This method is complicated and does not make too much business or economic sense. 

## Method-1

In [9]:
# creating two subsets of data.
deregulated_1985 = state[state['deregulation']==1985] # this gives us the entire data for all the states for which deregulation year was 1985.
deregulated_1987 = state[state['deregulation']==1987] # this gives us the entire data for all the states for which deregulation year was 1987.

In [10]:
# creating the treatment group.
# the time period that has to be considered is 1985 to 1987.
# the cumulative is taken for all the states which implemented inter-state deregulation in the year 1985.
x = deregulated_1985[deregulated_1985['year2']>=1985] # taking the data for all years from 1985.
y = x[x['year2']<=1987] # taking the data for years from 1985 to 1987.
final_value_1985 = [] # this will contain the cumulative of number of firms in each firm size from 1985 to 1987.
for i in category:
    final_value_1985.append(y[y['fsize']==i]['Firms'].sum())
    
print(final_value_1985) # gives us the total number of firms from 1985 to 1987 in each firm size.
print('---------------')
print(final_value_1985[0]) # corresponds to the total number of firms from 1985 to 1987 in firm size 'a) 1 to 4'.

[1443947, 581656, 325466, 196226, 65501, 41593, 18314, 13168, 14014, 8585, 7617, 13345]
---------------
1443947


In [11]:
x = deregulated_1985[deregulated_1985['year2']==1985] # taking the data for the year 1985.
initial_value_1985 = []
for i in category:
    initial_value_1985.append(x[x['fsize']==i]['Firms'].sum())
    
print(initial_value_1985) # gives us the total number of firms in 1985 in each firm size.
print('---------------')
print(initial_value_1985[0]) # corresponds to the total number of firms in 1985 in firm size 'a) 1 to 4'.

[465605, 185861, 103091, 61937, 20440, 13095, 5783, 4249, 4427, 2655, 2437, 4317]
---------------
465605


In [12]:
# creating the control group.
# the time period that has to be considered is 1985 to 1987.
# the cumulative is taken for all the states which implemented inter-state deregulation in the year 1987.
x = deregulated_1987[deregulated_1987['year2']>=1985]  # taking the data for all years from 1985.
y = x[x['year2']<=1987] # taking the data for years from 1985 to 1987.
final_value_1987 = []
for i in category:
    final_value_1987.append(y[y['fsize']==i]['Firms'].sum())
    
print(final_value_1987) # gives us the total number of firms from 1985 to 1987 in each firm size.
print('---------------')
print(final_value_1987[0]) # corresponds to the total number of firms from 1985 to 1987 in firm size 'a) 1 to 4'.

[1857554, 726624, 411707, 250176, 81034, 46764, 18306, 12087, 12689, 7420, 6420, 11148]
---------------
1857554


In [13]:
x = deregulated_1987[deregulated_1987['year2']==1985] # taking the data for the year 1985.
initial_value_1987 = []
for i in category:
    initial_value_1987.append(x[x['fsize']==i]['Firms'].sum())
    
print(initial_value_1985) # gives us the total number of firms in 1985 in each firm size.
print('---------------')
print(initial_value_1985[0]) # corresponds to the total number of firms in 1985 in firm size 'a) 1 to 4'.

[465605, 185861, 103091, 61937, 20440, 13095, 5783, 4249, 4427, 2655, 2437, 4317]
---------------
465605


In [14]:
# taking the percentage change in the treatment group between 1985 and 1987.
change_1985 = (((np.array(final_value_1985) - np.array(initial_value_1985))/np.array(initial_value_1985)) * 100)
print(change_1985)

[ 210.12274353  212.95215241  215.70748174  216.81547379  220.45499022
  217.62504773  216.68684074  209.9082137   216.55748814  223.35216573
  212.55642183  209.12670836]


In [15]:
# taking the percentage change in the control group between 1985 and 1987.
change_1987 = (((np.array(final_value_1987) - np.array(initial_value_1987))/np.array(initial_value_1987)) * 100)
print(change_1987)

[ 205.4433939   206.8824543   207.49645231  207.2396134   209.08952207
  208.24599565  205.50734312  206.3878327   211.69245886  228.02829355
  213.93643032  204.67340803]


In [16]:
# Taking the change between the treatment group and the control group to find out percentage change
# due to implementation of inter-state deregulation in each firm size category between 1985 and 1987.
# Taking the difference in difference.
total_change = change_1985 - change_1987
print(category)
print(total_change)

['a) 1 to 4' 'b) 5 to 9' 'c) 10 to 19' 'd) 20 to 49' 'e) 50 to 99'
 'f) 100 to 249' 'g) 250 to 499' 'h) 500 to 999' 'i) 1000 to 2499'
 'j) 2500 to 4999' 'k) 5000 to 9999' 'l) 10000+']
[  4.67934963   6.06969811   8.21102943   9.57586039  11.36546815
   9.37905208  11.17949762   3.520381     4.86502929  -4.67612782
  -1.38000849   4.45330033]


## Method-2

In [17]:
deregulated_1985 = state[state['deregulation']==1985] # this gives us the entire data for all the states for which deregulation year was 1985.
deregulated_1986 = state[state['deregulation']==1986] # this gives us the entire data for all the states for which deregulation year was 1986.

In [18]:
# creating the treatment group.
# the time period that has to be considered is 1985 to 1986.
# the cumulative is taken for all the states which implemented inter-state deregulation in the year 1985.
x = deregulated_1985[deregulated_1985['year2']>=1985] # taking the data for all years from 1985.
y = x[x['year2']<=1986] # taking the data for years from 1985 to 1986.
final_value_1985 = []
for i in category:
    final_value_1985.append(y[y['fsize']==i]['Firms'].sum())

print(final_value_1985) # gives us the total number of firms from 1985 to 1987 in each firm size.
print('---------------')
print(final_value_1985[0]) # corresponds to the total number of firms from 1985 to 1986 in firm size 'a) 1 to 4'.

[946797, 379903, 211789, 127381, 42240, 26823, 11839, 8609, 9094, 5488, 5019, 8849]
---------------
946797


In [19]:
x = deregulated_1985[deregulated_1985['year2']==1985] # taking the data for the year 1985.
initial_value_1985 = []
for i in category:
    initial_value_1985.append(x[x['fsize']==i]['Firms'].sum())

print(initial_value_1985) # gives us the total number of firms in 1985 in each firm size.
print('---------------')
print(initial_value_1985[0]) # corresponds to the total number of firms in 1985 in firm size 'a) 1 to 4'.

[465605, 185861, 103091, 61937, 20440, 13095, 5783, 4249, 4427, 2655, 2437, 4317]
---------------
465605


In [20]:
# creating the control group.
# the time period that has to be considered is 1985 to 1986.
# the cumulative is taken for all the states for which implemented inter-state deregulation in the year 1986.
x = deregulated_1986[deregulated_1986['year2']>=1985] # taking the data for all years from 1985.
y = x[x['year2']<=1986] # taking the data for years from 1985 to 1986.
final_value_1986 = []
for i in category:
    final_value_1986.append(y[y['fsize']==i]['Firms'].sum())

print(final_value_1986) # gives us the total number of firms from 1985 to 1987 in each firm size.
print('---------------')
print(final_value_1986[0]) # corresponds to the total number of firms from 1985 to 1986 in firm size 'a) 1 to 4'.

[1128682, 449134, 257277, 159496, 53705, 33673, 13593, 9592, 10220, 5886, 5256, 9294]
---------------
1128682


In [21]:
x = deregulated_1986[deregulated_1986['year2']==1985] # taking the data for the year 1985.
initial_value_1986 = []
for i in category:
    initial_value_1986.append(x[x['fsize']==i]['Firms'].sum())
    
print(initial_value_1986) # gives us the total number of firms in 1985 in each firm size.
print('---------------')
print(initial_value_1986[0]) # corresponds to the total number of firms in 1985 in firm size 'a) 1 to 4'.

[558261, 220679, 125728, 77663, 26180, 16603, 6778, 4705, 4980, 2850, 2544, 4543]
---------------
558261


In [22]:
# taking the percentage change in the treatment group between 1985 and 1986.
change_1985 = (((np.array(final_value_1985) - np.array(initial_value_1985))/np.array(initial_value_1985)) * 100)
print(change_1985)

[ 103.34768742  104.40167652  105.43888409  105.66220514  106.65362035
  104.83390607  104.72073318  102.61237938  105.42127852  106.70433145
  105.94993845  104.9803104 ]


In [23]:
# taking the percentage change in the control group between 1985 and 1986.
change_1986 = (((np.array(final_value_1986) - np.array(initial_value_1986))/np.array(initial_value_1986)) * 100)
print(change_1986)

[ 102.17819264  103.52367013  104.62983584  105.3693522   105.13750955
  102.81274468  100.54588374  103.86822529  105.22088353  106.52631579
  106.60377358  104.57847238]


In [24]:
# Taking the change between the treatment group and the control group to find out percentage change
# due to implementation of inter-state deregulation in each firm size category between 1985 and 1986.
# Taking the difference in difference.
total_change = change_1985 - change_1986
print(category)
print(total_change)

['a) 1 to 4' 'b) 5 to 9' 'c) 10 to 19' 'd) 20 to 49' 'e) 50 to 99'
 'f) 100 to 249' 'g) 250 to 499' 'h) 500 to 999' 'i) 1000 to 2499'
 'j) 2500 to 4999' 'k) 5000 to 9999' 'l) 10000+']
[ 1.16949478  0.87800639  0.80904826  0.29285294  1.5161108   2.02116139
  4.17484944 -1.25584591  0.20039498  0.17801566 -0.65383514  0.40183803]


## Method-3 (Matrix method)

In [25]:
matrix = np.array([[[0.0]*12]*51]*51) # creating a 3D matrix of 51*51*12 having all entries as 0.0
loop1 = 0
for i in st_code:
    loop2 = 0
    for j in st_code:
        year_dereg_1 = dict_year[i] # inter-state deregulation implementation year of state-i
        year_dereg_2 = dict_year[j] # inter-state deregulation implementation year of state-j
        val_1 = state[state['deregulation']==year_dereg_1] # only those states for which inter-state deregulation 
                                                          # implementation year is same as state-i.
        dereg_1 = val_1[val_1['state']==i] # taking only state-i. # this is the treatment group for this iteration.
        val_2 = state[state['deregulation']==year_dereg_2] # only those states for which inter-state deregulation
                                                          # implementation year is same as state-j.
        dereg_2 = val_2[val_2['state']==j] # taking only state-j. # this is the control group for this iteration.
        if year_dereg_2 < year_dereg_1:
            value = np.repeat(np.nan, 12) # if deregulation year of state-j is less than state-i then we 
                                        # cannot do difference in difference between then because it becomes opposite.
        
        else:
            a = dereg_1[dereg_1['year2']>=year_dereg_1] # taking the data for all years from year_dereg_1.
            b = a[a['year2']<=year_dereg_2]  # taking the data for all years from year_dereg_1 to year_dereg_2.
            final_value_dereg_1 = [] # to store the total number of firms from year_dereg_1 to year_dereg_2 in each firm size.
            for tmp1 in category:
                final_value_dereg_1.append(b[b['fsize']==tmp1]['Firms'].sum())
                
            c = dereg_1[dereg_1['year2']==year_dereg_1] # taking the data for year_dereg_1.
            initial_value_dereg_1 = [] # to store the total number of firms in year_dereg_1 in each firm size.
            for tmp2 in category:
                initial_value_dereg_1.append(c[c['fsize']==tmp2]['Firms'].sum())
                
            change_dereg_1 = (((np.array(final_value_dereg_1) - np.array(initial_value_dereg_1))/np.array(initial_value_dereg_1)) * 100)
            # percentage change from year_dereg_1 to year_dereg_2 in the treatment group.
            
            d = dereg_2[dereg_2['year2']>=year_dereg_1] # taking the data for all years from year_dereg_1.
            e = d[d['year2']<=year_dereg_2] # taking the data for all years from year_dereg_1 to year_dereg_2.
            final_value_dereg_2 = [] # to store the total number of firms from year_dereg_1 to year_dereg_2 in each firm size.
            for tmp3 in category:
                final_value_dereg_2.append(e[e['fsize']==tmp3]['Firms'].sum())
                
            f = dereg_2[dereg_2['year2']==year_dereg_1] # taking the data for year_dereg_1.
            initial_value_dereg_2 = [] # to store the total number of firms in year_dereg_1 in each firm size.
            for tmp4 in category:
                initial_value_dereg_2.append(f[f['fsize']==tmp4]['Firms'].sum())
            change_dereg_2 = (((np.array(final_value_dereg_2) - np.array(initial_value_dereg_2))/np.array(initial_value_dereg_2)) * 100)
            # percentage change from year_dereg_1 to year_dereg_2 in the control group.
            
            total_change = change_dereg_1 - change_dereg_2 # difference in difference. the effect of inter-state deregulation.
            value = total_change # temporary within the iteration variable.
    
        matrix[loop1][loop2] = value
        print(matrix[loop1][loop2])
        loop2 += 1
    loop1+=1            

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  4.55940772   1.83623214   7.54899455  15.0060873   26.07853223
  16.5353414   12.27397657  28.05494505  17.03110935  -3.01204819
 -16.3269466  -10.58339191]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.08265163 -0.19281222  4.07068501  6.18837242 -0.66056155  2.94959857
 -4.84530558  6.41463415  4.71410102  6.16668629 -7.40423784 -4.20748624]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.60459238 -1.69288499 -7.21804333 -0.26492703 -5.49662712 -4.71964008
 -8.44181288 -0.61370717 -1.65880166 -0.71915569 -3.58744395 -7.85417637]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  

[ 48.36466765  60.87380861  54.75981665  24.51152548  88.50439883
  33.78710531   8.35080363  30.77593723 -19.51886277  76.76730486
 -24.32983683  21.21434263]
[  41.77675342   13.27925053    0.96619956  -50.25407501   21.4591903
   -5.48221079  -61.50997151  -92.81326781  -33.96543044  205.95238095
  -19.78021978   38.99901478]
[  83.56577407   67.79448748   45.70628287    7.98358237   89.90919035
   26.53003896   26.41959857  -28.25870151    4.14182064  111.41758242
   22.27736421   49.51850312]
[  97.61904003  101.62176934   79.25759904  -13.26877513   87.64556284
   44.58037057   26.39540949   18.97642323  -50.28991971  181.48148148
  -30.70669168   56.47364621]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 54.24755394  54.5771303   44.63761506   9.56916533  70.22292158
  17.557516    -4.08781463   2.44197138 -23.51970064  93.36016097
  18.64253394  21.24444444]
[ 173.17052215  213.57712702  182.49750869   50.01652406  187.82853431
  -29.08708003  184.12698413  308.80557977  

[ 2.686477   -0.8321395  -0.43320134  1.12123319 -2.07251799 -0.22512201
  0.2576779   7.9786036  -2.51347056 -5.37704209  7.01404405  2.84215784]
[  7.32075897   6.58320742   7.72612464   3.25890072  -0.89304975
  10.52707736  21.58202247  -0.28028028 -21.24009731  32.86622938
  -2.72435897   2.67651888]
[ -5.43656313  -1.70446776  -1.10565298   0.28554246  -2.24579431
 -11.16420894   9.92941176   5.53197826  -3.04796757  -9.47100947
  18.2155827    3.63911649]
[  6.13212606   6.56284524   8.05598018  14.43635913  13.13685875
   3.01691552  22.9258216   22.3536036    4.30362161  -8.11965812
   9.93589744   4.34065934]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  n

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -0.77420898  -1.63984634  -1.10746434  -2.49940736   6.48845367
  -1.2234556    1.33287127   4.62266655  -7.77848235 -17.66424915
   3.91488414  -3.48575712]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  n

[  36.65998027  111.93278794  145.81318961  113.27112085   94.51885283
   79.61022282  137.76963777  113.05039788   91.03978436  -83.21772209
   17.33318481   86.26601669]
[ -0.51571358   4.25704536   8.16483677   1.67961657   2.46600978
   3.96410273  16.04296251  -3.41653666   5.13561434  16.68705403
   6.97279728  -1.89603421]
[ 12.63848514  38.83727397  68.57813297  75.4850826   62.16460634
  42.46158171  12.6017501   20.42735043  38.38562753  20.66572571
  15.3453637  -11.85767457]
[ -6.98570425   5.36985869   4.20860014   0.14848649 -13.88125623
   5.61969814  -3.2878424    6.68697639  27.90700587  33.12703267
  -1.70239389 -12.65631442]
[  5.44144864   3.89876799  14.61853156   0.86048556  11.777172
  24.38597801  11.62824937  -1.64398016  12.92406788  16.59746869
   0.68633374 -17.77781382]
[  1.0093064   -0.71644678   1.74124092  -1.62319     -0.89661383
  -2.35024126   3.4197961   -9.25393883   8.61003344  -5.74014381
  13.7122912    1.64954491]
[-46.36378814 -27.13229741 -11

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  2.46529184  -2.61145131  -3.9810029   -3.39941478  -2.47879476
  -4.87897633   1.7822106   -5.0877193    2.77473625  10.73313783
 -14.06844106   0.75075603]
[ 1.16512302 -0.15616166 -0.88646813  2.188965   -1.20493625 -0.10323175
  7.40989779 -8.70302645  6.87298036  8.96346644 -4.22535211  0.50703612]
[ -1.03549911  -3.94725056   7.49160525  19.21352107  19.86787266
   8.09433451  24.9000999   -7.43083671  38.02594218  26.66259915
 -51.89700041  32.12148992]
[-1.20251733 -3.50771456 -2.26694308 -1.17801586 -0.77270672 -5.04375766
  7.87451985 -2.9679782   5.51841939  9.21459493 -7.25806452 -2.14564136]
[ -15.16851602    1.74309997   45.19139217   81.95466642  115.13397408
   88.19216836   21.8495935    19.88304094  -96.72443153   79.73484848
  -21.02040816  153.56974804]
[  9.75885649  -1.02015571  12.51617031  34.69178033  30.93673846
  23.2426819   -8.09806136  16.27182

[ 12.22925145  12.62258761  14.91772034  17.01909669  19.52662722
  18.78118083  14.01077882  19.95875919   9.76345433  -0.62982769
   5.72657542   8.48636617]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  2.47885886  -8.36750019  -6.21256716  -7.69261927  22.4048982
  -2.40618939  62.73581213 -13.76165501  12.44067797  60.60606061
 -50.43696275   3.11241412]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  5.64821236   6.12467574  -0.13388582   3.39262843   7.85808156
   2.81178551   1.98956295   0.21101705   9.03534228  -6.25432406
  -4.68134657  17.82945736]
[ 23.76887279  20.00943698  16.82888269   9.65237598   9.81665247
  17.4217065   30.82519761   6.03821375   2.56971022  52.74170274
  -3.16218798  19.43047172]
[ 18.94179667  15.0305202   13.67678804  14.98662872   3.78978511
   3.9246476   16.64318838   0.65282279   3.33160222  -3.04936154
   0.86938291  16.66666667]
[ 21.72864951  19.5732648   20.67274698  29.46928166  32.59195385
  13.81562467  42.87493

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ -0.1777295    2.02721293  -0.42314189   1.09845154  -2.54033026
  11.54198731  -7.12021637   2.74028156  -2.12310935 -13.07843137
  -1.30799248  -0.59165509]
[ -0.25808045   1.32959668  -2.01512136   0.48163219  -3.72025058
  10.878331    -7.46031746   0.49848674  -7.43421716 -18.2457568
  -1.46396396   3.04176961]
[  43.20831435   70.23373629   80.33674733   60.12195476   44.63426442
  126.79937289  -20.39511248    5.98889157  -65.01121305  -27.58346582
 -113.35723479   35.95700964]
[  59.58006377   76.42143348   85.51551225   91.3781748    79.53024773
   93.04195087   -6.34920635   27.09278098  -44.03998553  -13.69795109
 -100.8666275    65.12652051]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  9.33701064  16.53770147  20.43641579  22.0927      25.77493917
  40.34447346 -13.9329806   24.42765225   2.58276825 -26.43084261
 -10.36036036   4.50979941]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0

[-19.27661328 -21.21625204 -17.09730208 -28.37292387 -22.18803419
 -15.76154276  -2.51004016   0.87171481 -33.52941176  -8.35770356
 -12.92598967  -0.93442066]
[ -2.51817473   0.68734244  -0.70912209  -6.09694428  -5.31684778
   4.627336     4.87662942  -3.88802488  -7.14285714 -17.1946749
   9.54365079  -1.27504554]
[  -7.96913814    8.84059248   15.93992277   11.69693647   -5.47625053
   16.14832536    8.65384615  -46.86248331   29.30320151 -113.60653851
   60.98901099  -23.40182648]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  18.2668065    48.23703942   87.51693509  112.3726124   106.79532164
   29.89158098  102.53979401  100.63965885  -65.66308244  -31.25524182
   41.97802198   36.18068936]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  9.67980846  14.03360134  23.0274228   10.06855914  13.82430862
  16.76959196  12.93103448   6.1646364   -5.34632035 -34.09107738
  35.24948735  -1.35433941]
[ -2.37932626  

[ -0.23063235  20.21663195  18.63398413  20.3786526   42.86152953
  19.48065338  12.66352695  22.00178099   7.14082258 -42.87439614
  14.04459691   2.51830386]
[-2.26425018 -0.37208267 -0.20568849 -0.0544033   0.41254132 -4.19157343
 -1.40526141 -1.61113396 -3.14987069 -0.07815291 -5.57683025 -7.63324394]
[ -2.07737079  11.01208331  15.23295938  18.51446376  18.0242279
   9.6176397   -0.75000593  10.19797812  13.1220486    6.83479532
   1.88811189  -1.75380618]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -7.44305072   1.86125944  -3.87878876  -3.7081264  -19.14389007
 -10.6285819  -38.75543062 -22.02068765  -2.88585654  -5.71581197
  -1.4229249  -12.38119388]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 

[ -0.38156822  -0.32309639  -1.83759358  -2.6610551   -1.20116884
 -13.40212953  -2.88827395   7.41347532  -9.86690806  17.39130435
   9.72850679  -3.65243004]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  na

[ -6.53024777  -2.60290501   4.58534955  -3.15667875   6.82898633
  15.94171379  22.49606328  30.06765974   2.19283747 -14.74890631
 -16.44907449   4.01877402]
[-39.94635705  -9.01439129  11.8307257   -2.23905819  32.89216905
  20.99121576  31.79071836   0.6300813   41.03812317  -7.43619698
  18.52722132  12.58808338]
[  6.99534634   9.03804423  19.22522454  24.90857463  18.11814433
  26.33574195  33.31433637  -1.96957776  22.54545455  -5.28846154
  -6.60677654  -1.22415219]
[  7.90031258  24.37948644  39.27926816  41.32573455  79.8396185
  42.55612215  19.72306653  77.20092915  36.01913876  43.38942308
   3.5654393   16.35375924]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -1.87448722  -5.20093449  -7.51751631  -4.88547164  24.00968885
   9.76511355  12.02856684   3.65367117  -6.323561   -16.90525941
  -3.683757    -7.60364004]
[ 0.  0.  0.  0.  0.  0.  0

[-22.11036286   7.33325755  13.47326328  34.62265126  70.25510031
 -83.70923169   4.56881782 -19.36009607  -0.20703934 -50.5952381
 -35.56289568 -37.98155867]
[  -0.91796507   88.38910995   85.90165243  125.29002104  242.82289386
   98.46738577    5.82524272   62.44582627  144.27302478  -72.32574189
  -28.33943834  -83.16498316]
[   2.02701063   40.13946185   51.30290767   45.21515534  110.35580524
  -53.00745042   28.73949238   61.44009147   72.74807572  -88.83858708
   66.06389391  -35.73093573]
[-155.30263267  129.01807456  321.63118269  322.35490297  313.25822704
 -228.40182908   55.87752054  197.10344828  354.9386845   368.65079365
 -206.66666667  -19.12972085]
[  85.09045201  214.24858026  272.98535749  329.90211383  292.39793584
  125.03145022  255.18520809  111.4650302   287.55493221   69.42667614
   12.94903926  -49.56836536]
[-210.08674992 -125.46606839 -166.66079915  -91.05268819  -55.77046549
 -182.32131886 -211.55250735  -57.73301468 -228.63416776 -201.76813341
 -223.61416

[  2.71081022   0.5100367    2.97960703  -1.09447359  10.01576327
   1.98050385  11.53116017  -4.6713147   -0.77493261   7.22487467
  -4.1819628    0.82443767]
[ 25.32522952  36.67622032  49.32354217  51.1018709   55.88452954
  49.83221477  57.72342544 -35.93372538  45.06315958  12.67625694
  30.85055913   7.48964638]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  71.29399945   89.61404325  124.61631091  150.89171074  174.93616671
   60.96315865  166.48194611  115.44756635  -80.50060864  158.60428917
   33.90376144   81.97741632]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 20.68005548  20.13422907  33.41814333  24.20651571  42.2360096
  24.40462295  29.8404196   14.54044973   3.08135261  13.14017407
  12.52450309   9.1021636 ]
[  2.84965869   0.61279323   3.47459415   1.44527893  12.88896168
   3.82398665   7.41336077  -6.55252059   1.57087656  12.5577812
  -4.67799455  -0.72215422]
[  2.71058314   0.16811777  

[  8.05410042   8.10905163   9.12526608   5.64240647  14.45858134
  18.68500041  18.01497515  -3.43721877   9.50985028  -2.36180204
  -2.1729461   -2.85541753]
[  1.28598211  -0.51707686   0.56621479   0.54599346   1.12565798
  -0.43058443   7.87005989  -5.17995549   9.42978723 -16.30228955
  10.34013605   2.81239183]
[-43.75113636 -22.92201377 -17.48252207 -21.00068977 -16.93914731
 -24.85793562  19.03591982 -59.89278612   1.77549523 -25.1234312
  -2.66439909  -9.08730159]
[ 14.9906923   43.98255315  61.82311061  36.45545732 -41.07526882
  14.02188117 -34.10448218   3.91556427  45.26595745  29.99038577
 -13.13053523  37.20760234]
[ -3.39099505   1.45469011   1.94601598  -4.20129824   4.54571976
   3.39174186  -9.70184076 -11.12213289  11.53630287 -10.19983803
  -0.51961744   5.3758047 ]
[  4.99992244e+00   2.14001859e+01   2.03684795e+01   3.55419926e+01
   5.61889387e+01   3.10002629e+01   2.11506976e+01   5.86464574e+00
   1.08094889e+00  -1.73845696e+01  -5.16662361e-03   3.6485890

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 26.1547041   19.53631278   7.50732859   1.36764409  -7.76000053
  17.7790761  -18.40062112 -78.21434686  34.68861847 -48.74188312
  19.70933197   3.70100083]
[ 36.77091511  27.99369742  22.26136905  29.30968373  19.45916947
   6.90237017   4.42929293 -77.99217731  39.9948396    9.53185328
   2.28652566  -5.75829652]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  3.63236572   7.08460382   7.9960577    8.92013632  10.75159816
   9.68616316   7.82216842  -1.56699712   9.14104662   2.33294931
   7.40981156  -3.20624192]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  2.02671298  -0.18485018   6.88417681   9.28703079   8.05382329
   9.74428651  11.53439153  -8.45522792   7.31335016  21

[  1.13494856   8.48228226   9.20234296  11.9079774    5.91685101
  14.15434036   5.11210349  15.58946913  10.13853179   1.85153437
   0.63042221  -1.6969068 ]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -4.23073137  -0.66854161  -9.90940519 -10.31461275 -31.25126697
  -6.09188124 -32.8933212  -16.62919664  -5.86937335 -10.69907291
  -2.68061458 -12.32429451]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 25.70368498  30.50432099   0.15850125  -9.72642651 -20.71917624
  -1.1019161  -41.78013307 -26.51333479  33.48826542 -79.62688777
  24.21383648  16.92559469]
[ 34.57872215  40.12048276  12.11892487  10.2415

[  1.66429194   3.36308779   3.64915473   3.70413943  -0.03229348
   0.80441298  14.64167872  -6.         -18.25134785  15.0498858
 -14.65311005   9.47515017]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -8.14086817  -4.37947101   1.92891977 -14.19738224 -29.31789893
  20.37292495  -4.53208556 -48.80861609  -8.43702995 -69.05485598
 -13.19966583  12.03852327]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan 

[ 17.34152082  17.45155626  16.66527301  48.18184575  34.82698466
   9.62327995  39.20046434  51.6971917  -14.66666667  51.69923534
 -37.72727273   0.42696338]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  6.8714511   10.38126776  18.48530336   7.36360147  29.82932676
  -1.93059851  -7.46189295  23.85494505  15.59846792  21.2034953
 -10.77922078  15.00701262]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  2.30402724   3.93765149  10.18507865   2.79876231   6.25756136
  -8.30336733 -12.24687262   4.74796748   4.66119097  18.84597487
  -8.57869866   8.01567018]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  2.82596799   2.43757873  -1.10364969  -3.65453713   1.42149579
 -15.97260598 -15.84337992  -2.28037383  -1.71171171  11.96013289
  -4.76190476   4.36898004]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  n

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  6.88297107   8.11447398  12.15907511   0.23687369  22.20470337
   9.1514614    4.42205863  14.28433456   4.48107448 -36.3292612
  36.59525188  -0.73495393]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 3.8683739   4.84843895  8.64564839  4.91623644  9.8210258   7.79997191
  6.02680744  0.2715431  -1.81718664 -4.5071705  -0.97225273  4.5574476 ]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -4.9642641   -3.18923146 -11.19658871  -4.70694653  21.66398138
   1.49823816  36.36923806 -41.90394721   5.76312576 -24.0276739
 -26.33404105 -24.70547627]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 1.78669354 -1.14377225 -0.21066753 -2.93949618 -2.88585516  2.9697448
 -6.71703474  3.17739521 -0.50315919 -9.73556896  1.88175595  0.1

[-14.06386472   8.82319106   5.37975701  -5.94512452  -0.70788482
 -10.98459353  -8.7830741   -0.1674956   -5.49358636   4.54455991
   0.79019413  -2.64182009]
[ -6.78472406   8.68406848   4.26076012  13.08721927  42.47337782
 -13.32061214 -35.59265219  68.55587435  11.98226834 -67.74425287
  -8.79065041  22.50239245]
[ -7.13295702  -1.156538    -6.94493312   1.21155512 -34.41268604
  -8.37477245  -0.69444444  -6.87686572   3.72039796 -16.63793103
  17.35285225   2.60485923]
[ -62.22866765   59.02671254   64.4013179    25.80625687   64.7628232
   55.15095064  160.37061794  -46.37936393  -45.77784908 -142.51311844
  176.5625      106.60613771]
[ 17.67288281  57.26326568  31.21504983  44.49014483 -16.55882323
  69.19346212   5.46186386 -28.57390776  98.45075329  18.72306034
  52.99334812  35.91168229]
[-11.3340788    2.57188675   4.92152507   7.85176046  -2.44619564
   8.82394733  -2.21316943  27.97445554 -12.68499782 -37.1489513
 -38.88580931  -7.78413065]
[ -66.40376109  -82.48632468  

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 14.79001778  20.94097058  27.53185917  27.49422018  23.88546144
  22.86847554  25.53143609  11.52177925   2.89267336  -9.73844813
  17.99518138  14.35678749]
[ 0.37118402  2.29668863  0.5622204   3.84064412  1.97092263  5.25869759
  5.1514003  -5.37240537 -1.77818005  4.82404692 -1.36778116  2.82572102]
[ 0.23210848  1.85201317 -0.12038554  3.85592287 -1.97949544  2.01662437
  5.55693954 -0.98335026 -5.18697352  3.35612581 -1.65992255  1.48069178]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.68069609  0.34422131  0.73799329  1.03604051 -4.26473761 -1.7714774
  8.64308628 -7.8469022  -3.43274498  0.61028771  5.53822732  0.24773559]
[ 13.01412193  20.06163952  27.92280067  30.62808723  42.77294624
  35.0877193    8.78454996 -16.32756133   0.0930473   21.73798552
  49.32402482  16.57711443]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  7.245715    12.58537506  14.90352741  22.38303735  14.36884512
  23.2837993

[  13.3190752    79.45165681  120.67776226  126.49560432  161.73475276
  178.57017988  136.59968243   60.93294461 -125.63129122   31.8452381
  -39.35483871   78.11157144]
[ 19.35465577  27.84565932  50.26998099  47.42818286  54.37367199
  72.75539237  36.42588677  41.79310932 -36.61815202   9.29914913
   9.62009128  46.08901299]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[-20.18109014 -21.76420034 -13.23655859 -17.90880738  -8.42224089
 -12.20912174   0.68277378  11.05959948 -21.15538076  15.16124325
 -32.29339646   8.95481437]
[-2.02723347 -1.4551265   0.49330916 -1.79249161  0.81973461  2.01861768
  4.50087346 -2.57607153  0.99667774 -0.07316627 -4.04244053  0.88746744]
[ -7.82059051  18.47977258  31.31183841  36.61246388  24.26647348
  33.13076278  44.38401335 -44.5301218   54.02542373 -45.40870894
  28.45025942  -5.72269876]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[   7.91393625   57.05428637   95.323753

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 11.05609932  20.6443382    6.52518198   9.33380832  -4.48192877
  25.78447941   3.13299233 -37.17171717  39.48375291 -54.54545455
   7.90948865  10.98484848]
[ 19.83886327  34.37968304  31.73468722  45.935326    31.56067353
  25.37085383  33.5959596  -24.28904429  47.83369089  15.34534535
 -11.41304348   3.35578002]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  5.44976722   6.35481999   8.21695112   8.76380395  11.43363554
   6.20154149  17.04252322  -0.10577473   3.72125514   4.61469534
   8.94721853  -1.32736137]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  3.85768929   1.10359397   8.57724972  12.20094684   6.81026396
   9.1

[ 0.83511008 -1.32183221 -0.3021124  -2.22661404 -4.8807321   0.2939559
 -4.36528015  8.45915842  0.07300272 -8.87597371  2.36213171 -0.38962852]
[  3.5499956    5.93374987   9.59113259   1.43089856  -3.62471349
  11.20369936  14.99460525   1.76384305 -20.00438899  27.63118664
 -13.87337058  -2.63157895]
[ -7.28793005  -2.19416047  -0.97456404  -3.06230477  -5.05400843
 -10.64513104   5.30645371   6.01253307  -0.46149428 -12.96994109
  13.56367037   0.40733013]
[  4.28075914   6.07315253   8.18706912  11.0885119   10.32864464
   3.53599342  18.30286354  22.83415842   6.89009489 -11.61858974
   5.2839851    1.10887298]
[  5.48066599   0.18081098  -1.02554718   2.73132046 -14.19227637
  -6.64110809 -17.1076477   34.52862927 -35.23448061 -31.94542877
  38.39473684 -24.13171855]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -6.50751113  -7.16427541  -8.29441657 -20.79410474 -26.41446498
 -24.50273442   6.0158883  -21.13938693 -43.00081683   4.1086003
  34.32330827 -17.252

[ 11.25779342  17.0110376   21.5617457   11.66077265  33.76649381
  27.67192768  70.53716326 -16.10238857  35.71459274 -20.60987273
  17.14478244   4.63083613]
[ -0.47178677  -0.91330179   1.37204282  -2.63168636  -0.73776393
  -2.16355829  12.08757487  -9.2031005    4.92274185   3.9580851
  -7.82914936  -5.91861118]
[  4.45523944   8.74699695  16.84739752  13.27845813  12.87131512
  13.93425093  36.96038494 -10.76560575  31.66447079  17.39246594
   1.75824176  -0.49623431]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -0.91044049  -0.40382692  -2.26435063  -8.94413202 -24.29680286
  -6.31197067  -1.04503974 -42.98427152  15.65656566   4.84185865
  -1.55279503 -11.12362201]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan 

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  0.12794441   1.33677097  -3.19241478  -1.11896944   7.11586832
   1.07472963   6.97769777   0.70921986 -11.06010252  -8.14275263
  -1.17670202  -2.81734133]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -1.72180813  -2.30187499  -3.42386922  -3.96938377  -0.94604337
  -0.67032722  -0.6457404   -9.08286757   0.64628853  -7.02165379
  10.7987536    0.17241379]
[ 14.87422932  19.35042918  29.84900666  17.97898593  41.71215557
  40.36857582  38.92131318   2.30530617   6.18387771 -21.26738644
  23.68627813   6.60248147]
[ -3.09760755  -2.46077987  -2.98333114  -3.53957474   8.47136346
   0.03346201  12.60769174 -14.5463712    5.

[  0.36439297  -2.206865    -3.85056763  -0.01805331  -1.24119232
  -3.77554791  16.96295706   7.52645698  -9.71408666  -4.34886128
  -1.10698125   1.08412606]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[   3.47847151   -6.90533984  -13.64488509  -10.12870883   -2.15164752
   41.76784089   89.61163949  -97.00229993 -147.19009124   41.69774011
    0.29671389   24.1610558 ]
[  3.48661216  -8.80805015 -15.20330273  -2.37957728   3.41119153
  -1.00641396   1.55815972 -46.54791252 -32.3847561    6.04622871
  -9.77878331  -3.96208137]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -2.56427237  -5.16458835  -2.82925378   0.26671705  -4.07597689
 -13.96492926  16.00676467 -21.02426762  -6.04194316   6.05128205
 -18.64216606   3.0625332 ]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan

[ -43.66104044  -36.48845109  -58.30256972  -48.807083   -104.23075094
  -62.79094636  -13.38709677  -42.95522388   62.44067797   44.68954248
  -90.55023923   -8.71926815]
[-13.25376286  -9.79515874  -5.64831727  -4.24102341   0.36522485
  -4.74901221  -2.06975024 -14.13107729   5.64588286  -8.9869281
  -4.78862701  -4.50985728]
[ -9.09375344  -8.05678582  -3.56261954  -7.30784936  12.90198052
 -11.68944461   3.03925379 -24.3614144   12.70952981 -41.99249605
 -26.97255575  -1.25940692]
[-43.16293246 -17.38469043   0.47520711 -15.31005732  40.76263155
 -18.04961951  10.75924469 -66.45522388  52.56971022 -43.6007269
  10.17952636   5.2441066 ]
[  4.43184067   3.58416342  11.07725544  20.75740402  24.19113853
  -1.29541645  13.85752688 -56.3986519   33.06214689 -32.53205128
 -17.1302578   -6.50233313]
[  5.3368069   18.92560563  31.13129906  37.17456394  85.91261269
  14.92496376   0.26625704  22.77185501  46.5358311   16.14583333
  -6.95804196  11.0755783 ]
[ nan  nan  nan  nan  nan  nan

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  58.53138512   96.3820755   116.42811579  181.75125918  173.43168527
   23.44494626  184.00909225  152.1714228   -23.90767276   94.27575908
   35.17322372   85.39861626]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 17.54333846  23.13606064  31.99419128  29.01828565  38.07392857
  23.28580418  31.73585904  23.55329239   8.55594078 -12.18758829
  22.62135213   8.81261091]
[ 1.40062645  2.15574646  3.25351607  2.73254563  7.32330107  4.39371639
  8.05049669 -1.02882445  2.64277697 -1.22743111 -0.36350418  1.04111482]
[ 1.26155091  1.711071    2.57091013  2.74782439  3.372883    1.15164317
  8.45603592  3.36023066 -0.7660165  -2.69535221 -0.65564558 -0.30391442]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  1.71013852   0.20327914   3.42928896  -0.07205798   1.08764083
  -2.6364586   11.54218266  -3.50332128   0.98821204  -5.44119032
   6.5425043   -1.53687061]
[ 18.08866131  27.07291917  33.52763142  37.43077314

[ -14.3048208    -3.25885029  -28.96285213  -63.61194982  -51.5638283
   36.58217925   22.86312849  -42.82385834  -72.81925075  119.09090909
  -40.3676261     1.68539326]
[ -1.03205545   4.10818503  -2.85374917  -4.79763435   2.64274691
  11.44597291   4.56696279 -25.70484153  24.02515723  16.96428571
  -8.60582106   4.92957746]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -1.81423712   1.48689131   0.8881208    4.72378542   3.22560082
   5.67120047  -3.60951897 -10.23166023   5.90572949  23.40225564
  -5.66525771   0.40921203]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -4.00336988e-02   9.22552027e+00   4.18781999e+00  -5.04439253e+00
  -6.51122470e+00   6.07802747e+01  -2.12523277e+01  -2.74847428e+01
   1.87042302e+01   9.03325123e+01  -3.32198995e+01   2.38430

[   7.4256111    -6.05727927   -6.85499915   -4.62628942   55.76388889
  -28.59947644  102.24184783  -43.70286576 -106.19863014  -59.56416465
  -56.47422191  -26.55715681]
[  5.1984247  -10.11365801 -16.40304405  -6.96065839  20.34087612
 -33.53978979  -9.44444444  -9.66153846 -30.74101796 -41.65218399
 -45.41062802 -21.78319459]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ -0.75704825  -6.89822524  -3.63230131  -4.2710618    4.23448532
 -35.88728191  21.8010355    2.92434838 -13.01300578 -19.93284493
 -36.79745493  -6.49635838]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[  5.325278    -4.335657    -8.39442352  37.95042353  47.26178701
 -52.07004253  77.73026316   7.59109312 -19.98287671 -58.2010582
 -65.05016722 -25.50977944]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan 

In [26]:
print(category)
print('----------')
print(matrix[1][1]) # gives all 0's because you are comparing the state-1(ALABAMA) to itself.
print('----------')
print(matrix[2][3]) # the treatment group is state-2 and the control group is state-3 and the difference in difference is taken.
print('----------')
# You can see that the difference in difference values are large and therefore this method of comparison does not 
# make too much business or economic sense.

['a) 1 to 4' 'b) 5 to 9' 'c) 10 to 19' 'd) 20 to 49' 'e) 50 to 99'
 'f) 100 to 249' 'g) 250 to 499' 'h) 500 to 999' 'i) 1000 to 2499'
 'j) 2500 to 4999' 'k) 5000 to 9999' 'l) 10000+']
----------
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
----------
[ 12.99302105  21.69833126  12.93724629  12.37912131  32.69088506
  27.76177817  44.36923077  19.43347842   8.04919192 -45.22482349
  32.2841074   10.39635016]
----------
